spring.application.name=demo
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.datasource.url=jdbc:h2:file:C:/academia/src/demo0227/data/demo0227;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/schema-persistent.sql

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.model
mybatis.configuration.map-underscore-to-camel-case=true

spring.mvc.hiddenmethod.filter.enabled=true
